### ISSUE TITLE
[Feature Request] some feature request

### ISSUE THREAD

**Issue by liuxb** [LoveIsGrief/links-for-later#13]
Hi, I really like this extension, can you please add some feature options?

1: When browsing a website, the drop-down menu shows only the URLs that match the domain name of the current tab's website.
2: left clicking will not delete the URL.
3: The URLs in the pull-down menu can be opened using shortcut keys. By default, the number keys 1, 2, 3. . .
4: URLs can be sorted

This is a screenshot of a similar extension, but it has stopped development and is not compatible with 57
![Image](https://i.imgur.com/2oOVymp.png)

THANKS.

**Comment by LoveIsGrief** [comment]
Hi,

I had a look and can't seem to confirm:

>1: When browsing a website, the drop-down menu shows only the URLs that match the domain name of the current tab's website.

>2: left clicking will not delete the URL.

Which version of firefox are you using? I've tested this on 58 and 59.

Could you expand a little on the following point?

>3: The URLs in the pull-down menu can be opened using shortcut keys. By default, the number keys 1, 2, 3. . .

I'm not sure I understand the usecase:

 -  Should this be in the right-click or dropdown menu? 
 - Are all links numbered e.g 100 links = numbered from 1 to 100?

4 is fair, I can do that.

**Comment by LoveIsGrief** [comment]
The related issues should have resolved this
