### ISSUE TITLE
Store also the title of the linked page

### ISSUE THREAD

**Issue by hmijail** [LoveIsGrief/links-for-later#31]
It would be great if, together with the URL, the title of the destination page was also recorded.

Looks like when using the "Save link" contextual menu, the destination page is opened anyway for a moment in a new tab before the URL gets stored and the tab closed; I hope that capturing the title of that tab might be not too difficult :).

**Comment by LoveIsGrief** [comment]
Hi, this is a bug. As you correctly observed the destination page is opened for exactly this purpose. It works for some pages and for others it doesn't :frowning_face:
