### ISSUE TITLE
Web Extension

### ISSUE THREAD

**Issue by LoveIsGrief** [LoveIsGrief/links-for-later#4]
[Yay...](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)

- [x] Rewrite in webextension
- [x] Migrate data using [embedded webextension](https://github.com/mdn/webextensions-examples/tree/master/embedded-webextension-bootstrapped)
- [x] Release pure webextension

**Comment by LoveIsGrief** [comment]
Awaiting review for 1.0.0 embedded webextension

**Comment by Gitoffthelawn** [comment]
Great job!

**Comment by LoveIsGrief** [comment]
Thanks, @Gitoffthelawn  :)
